server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - StripPrefix=0

        # Event Service Routes
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=0

        # Booking Service Routes
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=0

        # Payment Service Routes
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0

        # Swagger Routes
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

        - id: event-service-docs
          uri: lb://event-service
          predicates:
            - Path=/event-service/v3/api-docs
          filters:
            - RewritePath=/event-service/v3/api-docs, /v3/api-docs

        - id: booking-service-docs
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/v3/api-docs
          filters:
            - RewritePath=/booking-service/v3/api-docs, /v3/api-docs

        - id: payment-service-docs
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/v3/api-docs
          filters:
            - RewritePath=/payment-service/v3/api-docs, /v3/api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Event Service
        url: /event-service/v3/api-docs
      - name: Booking Service
        url: /booking-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 0.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans